packages:
  - "apps/*"
  - "packages/*"
  - "packages/neurons/*"
  - "packages/synapses/*"
  - "packages/gateways/*"
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  nx: true
  sharp: true
  unrs-resolver: true
autoInstallPeers: true
strictPeerDependencies: false
